import React from 'react'
import { Container, Row } from 'react-bootstrap'

const Terms = () => {
  return (
    <Container className='py-5'>
      <h1 className="centered py-5">TERMS AND CONDITION</h1>
      <p>This Web Site Terms and Conditions of Use Agreement (the "Terms of Use") is between the party ("you") using The Site ("grpenterprise.com") and GRPEnterpise ("we" or "us"). You should carefully read the Terms of Use before using The Site. By using The Site you agree to be bound by the terms and conditions of use set forth in the Terms of Use. This is a legally binding agreement. If you do not agree with the Terms of Use you should not use The Site and must leave The Site.</p>
      <Row>
        <ol className="p-3">
          <li className="h6 mb-3">We agree to provide you access to The Site in accordance with the Terms of Use.</li>
          <li className="h6 mb-3">You agree to use The Site in a manner consistent with the Terms of Use and all applicable rules and regulations. You acknowledge that you have read the Terms of Use and that you accept the terms thereof. You agree to read these terms of use carefully before using The Site. If you do not agree to the Terms of Use, you may not access or otherwise use The Site.</li>
          <li className="h6 mb-3">You accept that The Site is provided on an 'as is, as available' basis.</li>
          <li className="h6 mb-3">The materials included in The Site are for general information purposes only and do not constitute legal advice. They are not intended to be a substitute for obtaining legal advice from legal counsel. ALL ARTICLES AND MATERIAL DISPLAYED BY US ON THE SITE ARE FOR INFORMATION ONLY, ARE NO SUBSTITUTE FOR SPECIFIC ADVICE, AND ARE IN NO MANNER TO BE CONSIDERED LEGAL ADVICE OR OTHER LICENSED PROFESSIONAL ADVICE OR A SUBSTITUTE THEREFOR. FOR SPECIFIC LEGAL ADVICE REGARDING YOUR PARTICULAR CIRCUMSTANCES, YOU MUST RETAIN LEGAL COUNSEL. We do not represent or endorse the accuracy or reliability of any advice, opinion, statement, or other information displayed or distributed through The Site. You acknowledge that any reliance upon any such materials, opinion, advice, statement, memorandum, or information shall be at your sole risk. We reserve the right, in its sole discretion, to correct any errors or omissions in any portion of The Site.  Any statement regarding past client enrollment or results, including but not limited to credit score improvements or credit item removals, are considered best estimations or are based on specific case studies conducted by GRP Enterprise.</li>
          <li className="h6 mb-3">YOUR ACCESS TO AND USE OF THE SITE MAY BE TERMINATED AT ANY TIME FOR ANY REASON OR FOR NO REASON BY YOU OR BY US.</li>
          <li className="h6 mb-3">WE MAY, SUBJECT TO AND IN ACCORDANCE WITH OUR PRIVACY POLICY FOR MARKETING AND OTHER PURPOSES, COLLECT, PROCESS AND TRANSMIT CERTAIN DATA OBTAINED FROM AND ABOUT YOU IN THE COURSE OF YOUR ACCESSING THE SITE. BY AGREEING TO THESE TERMS YOU AGREE TO SUCH DATA BEING SO USED AND FURTHER AGREE THAT IT MAY BE TRANSMITTED TO OTHERS WHETHER OR NOT WITHIN THE UNITED STATES IN ACCORDANCE WITH OUR PRIVACY POLICY AND UNDER APPLICABLE PRIVACY AND DATA PROTECTION LEGISLATION. Information on how and what type of data (if any) is held about you can be obtained by clicking here to review our privacy policy or by contacting us</li>
          <li className="h6 mb-3">The Site is protected by copyright as a collective work and/or compilation, pursuant to U.S. copyright laws, international conventions, and other copyright laws. You are authorized to download one copy of the material displayed or performed on The Site ('Content') on one computer for your personal, non-commercial use only but you may not in so doing remove or amend any trademark, copyright or other proprietary notice. All materials contained on The Site are protected by copyright, and are owned or controlled by us or the party credited as the provider of the Content. You will abide by any and all additional copyright notices, information, or restrictions contained in any Content on The Site. Permission is given to view the material on these web pages and save that material only for your personal reference. Copying or storing of any Content for other than personal, noncommercial use is expressly prohibited without the prior written permission from GRP Enterprise or the copyright holder identified in the individual Content's copyright notice.</li>
          <li className="h6 mb-3">Subject to the above, you may not modify, copy, distribute, republish or upload any of the material on The Site in any way unless you obtain the prior written consent of GRP Enterprise. No intellectual property or other rights shall be transferred to you through your use of The Site. We are not able to confirm that the materials contained on these web pages are correct in every case. GRP Enterprise reserves the right to make changes to The Site, including the availability of any feature, database, Content, Web page materials, product information and prices on The Site at any time without notice or liability. GRP Enterprise may also impose limits on certain features and services or restrict your access to parts or all of The Site without notice or liability.</li>
          <li className="h6 mb-3">To the extent that any portions of The Site (such as 'blogs') provide users an opportunity to post and exchange information, ideas or opinions ('Postings'), BE ADVISED THAT WE DO NOT SCREEN, EDIT, OR REVIEW POSTINGS PRIOR TO THEIR APPEARANCE ON THIS WEB SITE, and Postings do not necessarily reflect our views. To the fullest extent permitted by applicable laws, we exclude all responsibility and liability for the Postings or for any losses or expenses resulting from their use and/or appearance on The Site.</li>
          <li className="h6 mb-3">You represent, warrant and covenant that: (a) you shall not upload, post or transmit to or distribute or otherwise publish through The Site any materials which (i) restrict or inhibit any other user from using and enjoying The Site, (ii) are unlawful, threatening, abusive, libelous, defamatory, obscene, vulgar, offensive, pornographic, profane, sexually explicit or indecent, (iii) constitute or encourage conduct that would constitute a criminal offense, give rise to civil liability or otherwise violate law, (iv) violate, plagiarize or infringe the rights of third parties including, without limitation, copyright, trademark, patent, rights of privacy or publicity or any other proprietary right, (v) contain a virus or other harmful component, (vi) contain any information, software or other material of a commercial nature, (vii) contain advertising of any kind, or (viii) constitute or contain false or misleading indications of origin or statements of fact; and (b) that you are at least eighteen (18) years old.</li>
          <li className="h6 mb-3">We reserve the right to monitor all Postings or other materials posted on The Site and to remove any which we consider in our absolute discretion to be: (a) offensive, (b) inappropriate, (c) criminal or (d) otherwise in breach of these Terms of Use. We do not and cannot review all materials posted to The Site by users, and we are not responsible for any such materials posted by users. However, we reserve the right at all times to disclose any information as necessary to satisfy any law, regulation or government request, or to edit, refuse to post or to remove any information or materials, in whole or in part, that in the sole discretion of GRP Enterprise are objectionable or in violation of these Terms of Use.</li>
          <li className="h6 mb-3">You hereby represent and warrant that you have all necessary rights in and to all Postings you provide and all material they contain and that such Postings shall not infringe any proprietary or other rights of third parties. By posting messages, uploading files, inputting data or engaging in any other form of communication (individually or collectively 'Communications') to The Site, you hereby grant to GRP Enterprise, subject to our privacy policy, a perpetual, worldwide, irrevocable, unrestricted, non-exclusive, royalty free license to use, copy, license, sublicense, adapt, distribute, display, publicly perform, reproduce, transmit, modify, edit and otherwise exploit such Communications, in all media now known or hereafter developed. You hereby waive all rights to any claim against GRP Enterprise for any alleged or actual infringements of any proprietary rights, rights of privacy and publicity, moral rights, and rights of attribution in connection with such Communications.</li>
          <li className="h6 mb-3">You acknowledge that transmissions to and from The Site are not confidential and your Communications may be read or intercepted by others. Any unprotected e-mail communication over the Internet is subject to possible interception or loss, is not confidential and is also subject to possible alteration. We are not responsible for and will not be liable to you or any third party for damages in connection with Communications or an e-mail sent by you to us or an e-mail sent by us to you, or anyone you designate, at your request. Violators of this section who use our services for any illegal purpose including but not limited to repeated unwanted emails or 'Spam', may be prosecuted to the full extent of the law. You acknowledge that by submitting Communications to GRP Enterprise, no confidential, fiduciary, contractually implied or other relationship is created between you and GRP Enterprise other than pursuant to these Terms of Use and any subsequent written agreement entered into with GRP Enterprise.</li>
          <li className="h6 mb-3">THE SITE, INCLUDING ALL CONTENT, SOFTWARE, FUNCTIONS, MATERIALS AND INFORMATION MADE AVAILABLE ON OR ACCESSED THROUGH THE SITE, IS PROVIDED 'AS IS, AS AVAILABLE' TO THE FULLEST EXTENT PERMISSIBLE BY LAW. GRP ENTERPRISE AND ITS SUBSIDIARIES AND AFFILIATES MAKE NO REPRESENTATION OR WARRANTIES OF ANY KIND WHATSOEVER FOR THE CONTENT ON THE SITE OR THE MATERIALS, INFORMATION AND FUNCTIONS MADE ACCESSIBLE BY THE SOFTWARE USED ON OR ACCESSED THROUGH THE SITE, FOR ANY PRODUCTS OR SERVICES OR HYPERTEXT LINKS TO THIRD PARTIES OR FOR ANY BREACH OF SECURITY ASSOCIATED WITH THE TRANSMISSION OF SENSITIVE INFORMATION THROUGH THE SITE OR ANY LINKED SITE. FURTHER, GRP ENTERPRISE AND ITS SUBSIDIARIES AND AFFILIATES DISCLAIM ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. GRP ENTERPRISE DOES NOT WARRANT THAT THE FUNCTIONS CONTAINED IN THE SITE OR ANY MATERIALS OR CONTENT CONTAINED THEREIN WILL BE UNINTERRUPTED OR ERROR FREE, THAT DEFECTS WILL BE CORRECTED, OR THAT THE SITE OR THE SERVER THAT MAKES IT AVAILABLE IS FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. GRP ENTERPRISE AND ITS SUBSIDIARIES AND AFFILIATES SHALL NOT BE LIABLE FOR THE USE OF THE SITE, INCLUDING, WITHOUT LIMITATION, THE CONTENT AND ANY ERRORS CONTAINED THEREIN. FURTHER, IN NO EVENT WILL GRP ENTERPRISE BE LIABLE FOR ANY LOSS OF PROFITS, BUSINESS, USE OF DATA OR FOR INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES OF ANY KIND WHETHER BASED IN CONTRACT, NEGLIGENCE OR OTHER TORT. TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAWS, WE ON BEHALF OF OUR EMPLOYEES, AGENTS, SUPPLIERS, AND CONTRACTORS, DISCLAIM AND EXCLUDE LIABILITY FOR ANY LOSSES AND EXPENSES OF WHATEVER NATURE AND HOWSOEVER ARISING, INCLUDING WITHOUT LIMITATION ANY DIRECT, INDIRECT, SPECIAL, PUNITIVE, OR CONSEQUENTIAL DAMAGES, LOSS OF USE, LOSS OF DATA, LOSS CAUSED BY A VIRUS, LOSS OF INCOME OR PROFIT, LOSS OF OR DAMAGE TO PROPERTY, CLAIMS OF THIRD PARTIES, OR OTHER LOSSES OF ANY KIND OR CHARACTER, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES OR LOSSES, ARISING OUT OF OR IN CONNECTION WITH THE USE OF THIS THE SITE OR ANY WEB SITE WITH WHICH IT IS LINKED. YOU ASSUME TOTAL RESPONSIBILITY FOR ESTABLISHING SUCH PROCEDURES FOR DATA BACK UP AND VIRUS CHECKING AS YOU CONSIDER NECESSARY.</li>
          <li className="h6 mb-3">You hereby agree to indemnify, defend and hold GRP Enterprise, and all its officers, directors, owners, agents, employees, information providers, affiliates, licensors and licensees (collectively, the 'Indemnified Parties') harmless from and against any and all liability and costs incurred by the Indemnified Parties in connection with any claim arising out of any breach by you of these Terms of Use or the foregoing representations, warranties and covenants, including, without limitation, attorneys' fees and costs. You shall cooperate as fully as reasonably required in the defense of any claim. GRP Enterprise reserves the right, at its own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you and you shall not in any event settle any matter without the written consent of GRP Enterprise.</li>
          <li className="h6 mb-3">Where we provide hypertext links from or to third party sites we do so for convenience and information purposes only. We do not review, endorse, approve or control, and are not responsible for any sites linked from or to the Website, the content of those sites, the third parties named therein, or their products, resources or services. Linking to any other site is at your sole risk and we will not be responsible or liable for any damages in connection with linking, and we accept no liability nor make any endorsement or approval of the same.</li>
          <li className="h6 mb-3">These Terms of Use contain the entire understanding between us with respect of The Site and no representation, statement, inducement oral or written, not contained herein shall bind either of us. GRP Enterprise reserves the right, at its sole discretion, to change, modify, add or remove any portion of these Terms of Use, in whole or in part, at any time. Notification of changes in these Terms of Use will be posted on The Site.</li>
          <li className="h6 mb-3">Should any part of the Terms of Use be declared invalid or unenforceable by a court of competent jurisdiction, this shall not affect the validity of any remaining portion and such remaining portion shall remain in full force and effect as if the invalid portion of the Terms of Use had been eliminated.</li>
          <li className="h6 mb-3">The Site, any information provided from it and the Terms of Use are given and made in United States of America. THIS TERMS OF USE AGREEMENT SHALL BE GOVERNED BY AND CONSTRUED IN ACCORDANCE WITH THE LAWS OF THE STATE OF ILLINOIS, WITHOUT REGARD TO CONFLICTS OF LAWS PROVISIONS. SOLE AND EXCLUSIVE JURISDICTION FOR ANY ACTION OR PROCEEDING ARISING OUT OF OR RELATED TO THIS TERMS OF USE AGREEMENT SHALL BE AN APPROPRIATE STATE OR FEDERAL COURT LOCATED IN DU PAGE COUNTY IN THE STATE OF ILLINOIS.</li>
          <li className="h6 mb-3">Pursuant to Federal law we are providing the following separate written statement for your review and to acknowledge receipt thereof, which, pursuant to the requirements of Federal law, will also be delivered with any contract for credit report repair services entered into with The GRP Enterprise:</li>
          <li className="h6 mb-3">I agree to (1) be contacted about credit repair or credit repair marketing by a live agent, artificial or prerecorded voice, and SMS text at my residential or cellular number, dialed manually or by autodialer, and by email by GRP Enterprise and by it's partners regarding offers and notifications  (consent to be contacted is not a condition to purchase services).</li>
          <li className="h6 mb-3">I understand that results will vary.  I understand that The Site and GRP Enterprise do not guarantee any specific results or outcome to any individual.</li>
          <li className="h6 mb-3">The terms and conditions of use in this Terms of Use are subject to change at any time. You should review the Terms of Use regularly for any changes.</li>
        </ol>
        <h1 className="centered">Disclosure Statement Required Pursuant to Federal Law</h1>
        <h3 className="centered"><i>Consumer Credit File Rights Under State And Federal Law</i></h3>
        <p className="m-0 p-3">
          You have a right to dispute inaccurate information in your credit report by contacting the credit bureau directly. However, neither you nor any "credit    repair" company or credit repair organization has the right to have accurate, current, and verifiable information removed from your credit report. The credit bureau must remove accurate, negative information from your report only if it is over 7 years old. Bankruptcy information can be reported for 10 years.
          <br /><br />
          You have a right to obtain a copy of your credit report from a credit bureau. You may be charged a reasonable fee. There is no fee, however, if you have been turned down for credit, employment, insurance, or a rental dwelling because of information in your credit report within the preceding 60 days. The credit bureau must provide someone to help you interpret the information in your credit file. You are entitled to receive a free copy of your credit report if you are unemployed and intend to apply for employment in the next 60 days, if you are a recipient of public welfare assistance, or if you have reason to believe that there is inaccurate information in your credit report due to fraud.
          <br /><br />
          You have a right to sue a credit repair organization that violates the Credit Repair Organization Act. This law prohibits deceptive practices by credit repair organizations.<br /><br />
          You have the right to cancel your contract with any credit repair organization for any reason within 3 business days from the date you signed it.
          <br /><br />
          Credit bureaus are required to follow reasonable procedures to ensure that the information they report is accurate. However, mistakes may occur.
          <br /><br />
          You may, on your own, notify a credit bureau in writing that you dispute the accuracy of information in your credit file. The credit bureau must then reinvestigate and modify or remove inaccurate or incomplete information. The credit bureau may not charge any fee for this service. Any pertinent information and copies of all documents you have concerning an error should be given to the credit bureau.
          <br /><br />
          If the credit bureau's reinvestigation does not resolve the dispute to your satisfaction, you may send a brief statement to the credit bureau, to be kept in your file, explaining why you think the record is inaccurate. The credit bureau must include a summary of your statement about disputed information with any report it issues about you.<br /><br />
          The Federal Trade Commission regulates credit bureaus and credit repair organizations. For more information contact:
          <br /><br />
          <strong><i>The Public Reference Branch Federal Trade Commission Washington, D.C. 20580</i></strong></p>
      </Row>
    </Container>
  )
}

export default Terms